In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 11 금융 경제 데어 애플리케이션
#### 금융 분야에서 파이썬 사용률 증가
#### 장점
#### interpreter 형식
#### 관련 라이브러리 다양
#### 시스템 구축의 시간 절약 : 생산성 up

#### 초점 - 크로스섹션 : 시간 상 고정된 위치에 존재하는 데이터

## 11.1 데이터 준비

## 11.1.1 시계열과 크로스 섹션 정렬
#### 금융 데이터 : 데이터 정렬에 많은 시간 소요
#### 문제의 원인 
#### 1. 서로 다른 데이터의 시계열 인덱스의 불일치
#### 2. dataframe 객체의 행이나 열의 라벨 불일치

#### 여기서 pandas의 장점이 나타난다!!!!!
#### 산술 연산을 통해 자동적으로 데이터를 정렬하는 방식

In [8]:
import pickle

In [16]:
pd.read_json

NameError: name 'pydata' is not defined

In [14]:
pd.read_pickle('C:\\python\\DATA_SET\\yahoo_price.pkl')

                  AAPL        GOOG         IBM       MSFT
Date
2010-01-04   27.990226  313.062468  113.304536  25.884104
2010-01-05   28.038618  311.683844  111.935822  25.892466
2010-01-06   27.592626  303.826685  111.208683  25.733566
2010-01-07   27.541619  296.753749  110.823732  25.465944
2010-01-08   27.724725  300.709808  111.935822  25.641571
2010-01-11   27.480148  300.255255  110.763844  25.315406
2010-01-12   27.167562  294.945572  111.644958  25.148142
2010-01-13   27.550775  293.252243  111.405433  25.382312
2010-01-14   27.391211  294.630868  113.184773  25.892466
2010-01-15   26.933449  289.710772  112.731385  25.808835
2010-01-19   28.124939  293.516976  114.750251  26.009552
2010-01-20   27.692027  289.915587  111.422546  25.583028
2010-01-21   27.213337  291.199286  110.353231  25.097963
2010-01-22   25.863592  274.730736  107.359151  24.219826
2010-01-25   26.559391  269.730740  107.889534  24.520902
2010-01-26   26.934757  270.939526  107.573014  24.671439
2010-01-27   27.188489  270.779695  108.069178  24.813614
2010-01-28   26.065007  266.878565  105.862111  24.387091
2010-01-29   25.119401  264.705742  104.698697  23.567497
2010-02-01   25.468608  266.244198  106.649125  23.759851
2010-02-02   25.616400  265.295156  107.384814  23.801666
2010-02-03   26.057159  270.140309  107.496027  23.943840
2010-02-04   25.118093  263.127321  105.220523  23.283148
2010-02-05   25.564084  265.380075  105.665355  23.433686
2010-02-08   25.388826  266.468996  104.728745  23.182789
2010-02-09   25.659561  267.952522  105.871586  23.425323
2010-02-10   25.519617  266.958496  105.527873  23.408596
2010-02-11   25.983917  267.932539  106.318414  23.517319
2010-02-12   26.207567  266.294170  106.550416  23.358417
2010-02-16   26.602551  270.380071  107.607330  23.820544
...                ...         ...         ...        ...
2016-09-12  105.440002  769.020020  158.289993  57.049999
2016-09-13  107.949997  759.690002  155.809998  56.529999
2016-09-14  111.769997  762.489990  154.050003  56.259998
2016-09-15  115.570000  771.760010  155.660004  57.189999
2016-09-16  114.919998  768.880005  153.839996  57.250000
2016-09-19  113.580002  765.700012  154.869995  56.930000
2016-09-20  113.570000  771.409973  154.449997  56.810001
2016-09-21  113.550003  776.219971  155.529999  57.759998
2016-09-22  114.620003  787.210022  156.110001  57.820000
2016-09-23  112.709999  786.900024  154.979996  57.430000
2016-09-26  112.879997  774.210022  153.979996  56.900002
2016-09-27  113.089996  783.010010  156.770004  57.950001
2016-09-28  113.949997  781.559998  158.289993  58.029999
2016-09-29  112.180000  775.010010  158.110001  57.400002
2016-09-30  113.050003  777.289978  158.850006  57.599998
2016-10-03  112.519997  772.559998  157.610001  57.419998
2016-10-04  113.000000  776.429993  156.460007  57.240002
2016-10-05  113.050003  776.469971  157.080002  57.639999
2016-10-06  113.889999  776.859985  156.880005  57.740002
2016-10-07  114.059998  775.080017  155.669998  57.799999
2016-10-10  116.050003  785.940002  157.020004  58.040001
2016-10-11  116.300003  783.070007  154.789993  57.189999
2016-10-12  117.339996  786.140015  154.289993  57.110001
2016-10-13  116.980003  778.190002  153.720001  56.919998
2016-10-14  117.629997  778.530029  154.449997  57.419998
2016-10-17  117.550003  779.960022  154.770004  57.220001
2016-10-18  117.470001  795.260010  150.720001  57.660000
2016-10-19  117.120003  801.500000  151.259995  57.529999
2016-10-20  117.059998  796.969971  151.520004  57.250000
2016-10-21  116.599998  799.369995  149.630005  59.660000

[1714 rows x 4 columns]

In [12]:
f = open('C:\\python\\DATA_SET\\yahoo_price.pkl')

In [13]:
x = pickle.load(f)

UnicodeDecodeError: 'cp949' codec can't decode byte 0x80 in position 0: illegal multibyte sequence

In [11]:
%ls

 C 드라이브의 볼륨: Windows
 볼륨 일련 번호: E68C-5DCC

 C:\Users\HojaeLee\Python_Study 디렉터리

2018-04-03  오후 02:57    <DIR>          .
2018-04-03  오후 02:57    <DIR>          ..
2018-04-03  오후 02:18    <DIR>          .ipynb_checkpoints
2018-03-22  오후 02:52             3,230 APMonitor.ipynb
2018-02-12  오후 11:44             9,689 fig2.pdf
2018-02-12  오전 12:39             9,641 fig2n.pdf
2018-02-12  오전 12:33             1,197 figpath.pdf
2018-02-12  오전 12:33               618 figpath.svg
2018-03-26  오후 12:11            66,349 file that convert to csv.csv
2018-03-26  오후 09:55           182,218 HJ_proj_Bitcoin.ipynb
2018-03-07  오후 07:02         1,763,342 HJ_proj_WeatherDA.ipynb
2018-04-03  오전 11:49           480,417 PFDA_chap.10_Time_Series.ipynb
2018-04-03  오후 02:57            12,400 PFDA_chap.11_Finance_Economy_Application.ipynb
2018-03-23  오후 04:12            54,214 PFDA_chap.4_Numpy.ipynb
2018-03-26  오후 12:10           149,844 PFDA_chap.5_Pandas.ipynb
2018-03-26  오후 02:41           503,806 PFDA_chap.6_Data_Loading.ipynb
2018-03-26  오후 05:33           185,575 PFDA_chap.7_Data_preparing.ipynb
2018-03-26  오후 08:49           443,602 PFDA_chap.8_Matplotlib.ipynb
2018-03-26  오후 09:33           222,600 PFDA_chap.9_Group_Caculating.ipynb
2018-03-22  오후 02:50             1,562 what_time.ipynb
2018-02-07  오후 08:10           152,463 스터디_0207.ipynb
2018-01-31  오후 08:47             8,786 스터디0131.ipynb
              19개 파일           4,251,553 바이트
               3개 디렉터리  66,465,513,472 바이트 남음

In [10]:
pickle.load(open('C:\\python\\DATA_SET\\yahoo_price.pkl'))

UnicodeDecodeError: 'cp949' codec can't decode byte 0x80 in position 0: illegal multibyte sequence

In [4]:
open('C:\\python\\DATA_SET\\yahoo_price.pkl')

In [6]:
pd.read_table(open('C:\\python\\DATA_SET\\yahoo_price.pkl'))

UnicodeDecodeError: 'cp949' codec can't decode byte 0x80 in position 0: illegal multibyte sequence